services:
  server:
    image: ghcr.io/simongregorebner/gitea-pages:latest
    environment:
      GITEA_SERVER: https://git.example.com/
      GITEA_TOKEN: 91071xxxxxxxxxxxxxxxxxx97a
      # GITEA_PAGES_BRANCH: gitea-pages
      # GITEA_URL_SCHEME: simple
      # GITEA_PAGES_REPOSITORY: 
      # GITEA_POSTFIX_PAGES_REPOSITORY: 
      # LOG_LEVEL: INFO
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080/tcp"
